site_name: Lost Ark Mechaniki
site_url: https://github.com/BongoArmadillo/test
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: pink
  features:
    - navigation.sections
  features:
    - navigation.sections
extra_css:
  - styles/nav-dark.css
extra_javascript:
  - styles/sidebar-dark.js
nav:
  - Strona główna: index.md
  - Gate 1: gate1.md
  - Gate 2: gate2.md
  - Gate 3: gate3.md
  - Gate 4: gate4.md
  - Gate 5: gate5.md
  - Gate 6: gate6.md
